os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.4.0"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng test --browser PhantomJS --watch false
  - ng e2e
